return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 20,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 11,
  nextobjectid = 23,
  properties = {},
  tilesets = {
    {
      name = "terrain",
      firstgid = 1,
      filename = "lpc_terrain.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "terrain_atlas.png",
      imagewidth = 1024,
      imageheight = 1024,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 1,
      name = "ground 1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJy7xsTAcB2IbwDxTSC+BcTXoGLX8MjBxAjxKTWvC4i7gbgHiDvR+F1IGJccujg2dcSowaWOFPXEugkbnxw95NqFj08tc0bdN+o+cvjUNKsThxwp5qDLUTPsyOETUktt+wBwneeO"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 2,
      name = "ground 2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYMAPVhGQJxVQ27xRQB4IAOJAJBxEoXkFQFyIhIuoZB4Dlc0bKe6bAMQTkfAkCs0bBaMAGwAACrkP5g=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "player",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 3,
      name = "renderorder",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      layers = {
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 20,
          height = 20,
          id = 5,
          name = "stuff",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          properties = {
            ["ysort"] = true
          },
          encoding = "base64",
          compression = "zlib",
          data = "eJxjYBj8YAIjA8NEIJ4MxFMYKTdvA9CMjUC8GYi3kGFeJBMq/wLQjItYzNnNjMDYzICZg24eLnCbGYGRQRVQfzUQ1zChsnGBAzjkYOKzgPRsIJ7DhMrGBR5A5SYxotIPiPQXLrCJEZUmF/zGEv7EyFELzAPaMR+IF1BoFyyd7AOasx+ID1BgHnI6uQc05z4QP6DAPOR08g9ozn+QWSzkm0cumESF8gEZUJr2hjsAAH+cKTA="
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 20,
          height = 20,
          id = 8,
          name = "stuff2",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          properties = {
            ["ysort"] = true
          },
          encoding = "base64",
          compression = "zlib",
          data = "eJxjYBgFwwFUMTEwVANxDRN1zJsFNGc2EM+hknmDHfxkZGD4BcS/GaljniQw3KSAWJpK4WcJNMcKiK1HSHyMgqEBAFp/B0g="
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 4,
      name = "over1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzMERgCAQBMEj/wgUJQ8FzUNAY3Fi4B762Knq567Zv1qC2YoUxj8mtjMiCg6cjr+N7Y6MjhuP4+9iW9EcH0op9XUv20oNQg=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 7,
      name = "over2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgcYA4jA8NcIJ7HSB3z9gDN2QvE+6hk3h2gOXeB+B6VzBsFo2AUjIKhDgDOJAav"
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "collisions",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["collidable"] = true
      },
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 234.88,
          y = 260.193,
          width = 8.67582,
          height = 7.86751,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 492.884,
          y = 397.961,
          width = 6.58043,
          height = 6.28619,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 586.666,
          y = 411.747,
          width = 9.74191,
          height = 8.3081,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 556.321,
          y = 171.448,
          width = 5.84503,
          height = 6.05674,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 492.798,
          y = 172.514,
          width = 6.06561,
          height = 5.88191,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 460.945,
          y = 171.381,
          width = 5.84503,
          height = 6.01986,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 171.05,
          y = 237.808,
          width = 6.69048,
          height = 4.56779,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 362.889,
          y = 236.203,
          width = 7.86694,
          height = 4.4329,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 117.165,
          y = 100.385,
          width = 15.4396,
          height = 9.24229,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 53.895,
          y = 131.97,
          width = 17.1309,
          height = 9.85561,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 299.621,
          y = 260.535,
          width = 8.67582,
          height = 7.61836,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 267.365,
          y = 516.974,
          width = 8.67582,
          height = 7.53555,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0.802311,
          y = 0.802311,
          width = 245.507,
          height = 46.534,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 297.657,
          y = 3.20924,
          width = 341.784,
          height = 44.1271,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 638.639,
          y = 0.802311,
          width = 15.2439,
          height = 651.476,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1.60462,
          y = 640.244,
          width = 636.232,
          height = 11.2323,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = -11.2323,
          y = 0.802311,
          width = 11.2323,
          height = 650.674,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
